#pragma once

#include "core.hpp"
#include "math.hpp"

#include "graphics/exceptions.hpp"
#include "graphics/enums.hpp"
#include "graphics/resource_region_1d.hpp"
#include "graphics/resource_region_2d.hpp"
#include "graphics/resource_region_3d.hpp"
#include "graphics/display_mode.hpp"
#include "graphics/output.hpp"
#include "graphics/presentation_parameters.hpp"
#include "graphics/vertex_element.hpp"
#include "graphics/vertex_layout.hpp"
#include "graphics/vertex_structures.hpp"
#include "graphics/graphics_adapter.hpp"

#include "graphics/impl/graphics_resource_impl.hpp"
#include "graphics/graphics_resource.hpp"

#include "graphics/impl/vertex_buffer_impl.hpp"
#include "graphics/impl/index_buffer_impl.hpp"
#include "graphics/impl/swap_chain_impl.hpp"
#include "graphics/impl/occlusion_query_impl.hpp"

#include "graphics/swap_chain.hpp"
#include "graphics/occlusion_query.hpp"
#include "graphics/vertex_buffer.hpp"
#include "graphics/vertex_buffer_binding.hpp"
#include "graphics/index_buffer.hpp"
#include "graphics/shader.hpp"
#include "graphics/shader_group.hpp"
#include "graphics/shader_pipeline_stage.hpp"
#include "graphics/render_context.hpp"
#include "graphics/render_system.hpp"
